services:
  eda_pipeline:
    build: .
    container_name: eda_pipeline

    volumes:
      - ./data:/app/data
      - ./cleaned_data:/app/cleaned_data
      - ./reports:/app/reports

    command: tail -f /dev/null
    stdin_open: true
    tty: true